### ISSUE TITLE
Lock disk without unmounting manually

### ISSUE THREAD

**Issue by kowalski7cc** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#10]
Could be possible to make unmount the disk automatically when relocking instead of going to filesystem and unmount it manually so it will be remounted automatically next time you unlock it.

**Comment by imgrant** [comment]
Good point, manually unmounting a filesystem in order to lock the disk does have the side effect of the filesystem not being automatically mounted upon subsequent unlocking. However, I'm not sure I am convinced of the value of having a more powerful lock (that would also unmount filesystems), the current behaviour mimics the rest of OMV in making the user aware that X depends on Y, etc. Marking as won't fix, for the time being at least.
