### ISSUE TITLE
[Bug] OMV and LUKS for RAID (RAID1) not working after having setup up a password, the LUKS-RADI is not shown in the LUKS panel and no way to decrypt.

### ISSUE THREAD

**Issue by Wikinaut** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#24]
I don't see how OMV-LUKS is working for RAID, specifically in my case, for a RAID1.

Please can you elaborate

* how to set up -- I have setup OMV-LUKS for my RAID, but I don't see this listed in the LUKS overview, and there is no view to decrypt/delete the LUKS setup.
* how to use

**Comment by ryecoaaron** [comment]
Please post in the [forum](https://forum.openmediavault.org) for questions and to get wider visibility.

**Comment by Wikinaut** [comment]
@ryecoaaron uh, this is a bug. I have amended the title. After setting up LUKS, it is not shown again in the corresponding plugin panel, and also no way to monitor or remove (decrypt) the LUKS-RAID. Something is broken or generally spoken, not working.

**Comment by ryecoaaron** [comment]
Ok.  I mention the forum because you were asking how to use which tells me you were probably doing something wrong for a device not to show up in the plugin.

So, I will need more info.  Setting up LUKS how? Command line or plugin?  What kind of Raid? hardware, mdadm?  What version of OMV?  What kind of system?

**Comment by Wikinaut** [comment]
@ryecoaaron 
* OMV 0.6.14
* RAID1 with 2x10TB HDD - created with OMV
![grafik](https://user-images.githubusercontent.com/1151915/54958739-05d36580-4f57-11e9-9bac-b8935858f179.png)

* OMV luksencryption 3.0.5 - set up for the RAID1
![grafik](https://user-images.githubusercontent.com/1151915/54958754-1be12600-4f57-11e9-9cb9-31754602c45c.png)

=> nothing is shown any more, after I have set up the LUKS for the /dev/md0 .

**Comment by subzero79** [comment]
Much better information. Don't what you did, but that is wrong, the fs is sitting on the top of the raid block device directly. Once a block device (single or raid) has been encrypted it uses device mapper to show the un-locked device. So in case your md0 was encrypted in the column where it says 

/dev/md0 should say /dev/mapper/md0-crypt or similar.

Unmount the device, remove the fs(delete all data), clean any fs signatures then proceed to format with luks, once the device mapper appears format to ext4.

This was a question for the forum

**Comment by Wikinaut** [comment]
@subzero79 no matter what I do, I don't see any block device to apply LUKS, or to build a RAID from.

#### Tutorial with screenshots
Perhaps can you set up a tutorial with screenshots to explain the correct sequence to setup a RAID1 with LUKS using OMV and OMV-luksencryption plugin to fully exclude any possible mistakes of users?

**Comment by subzero79** [comment]
Wipe the Filesystem in md0, use delete filesystem. once that make sure blkid command in terminal doesn’t return any entries for md0. Then try again to create a Luks container with md0.

**Comment by Wikinaut** [comment]
* blkid shows only the system OMV) disks.
And now?

* I added a RAID1
![grafik](https://user-images.githubusercontent.com/1151915/54978645-3d66ff80-4fa1-11e9-842e-40386f104ec0.png)

What is the correct next step?

**Comment by Wikinaut** [comment]
I suggest you try it on your system and document here with your screenshots. I still suppose that something is wrong with the OMV-LUKS plugin. (In previous years I have set up several systems - without OMV - with RAID and LUKS manually).

**Comment by Wikinaut** [comment]
In other words: as soon as I use the OMV RAID module to set up my RAID1, I cannot see any available device in the OMV-LUKS module to set up a LUKS.

**Comment by subzero79** [comment]
The raid still has filesystem signature as you can see in the fs section shows ext4. just to be clear  you do realise you have to wipe the fs (delete data) right?

Destroy the raid in the corresponding panel, go to each disk and wipe them quick, then full for one minute each. Then after that create a new array, once is finish syncthing make sure no ext4 signature shows there, then go to luks to create an encrypted container from md0

**Comment by Wikinaut** [comment]
@subzero79 so I have to wait 807 minutes and then it will work??? Uh. then OMV needs a check so that OMV-LUKS is prevented unless sync'ing has finished.

![grafik](https://user-images.githubusercontent.com/1151915/55121781-5506cb00-50fc-11e9-8271-566278bdc71a.png)

**Comment by ryecoaaron** [comment]
You don't "have" to but using the array will slow down the sync.  Nothing OMV can do about that.  That is why OMV doesn't have a check to prevent it.

**Comment by subzero79** [comment]
There are ways of speeding a raid sync.

**Comment by Wikinaut** [comment]
@ryecoaaron 

When doing so as described:

![grafik](https://user-images.githubusercontent.com/1151915/55140926-7cc85400-5139-11e9-8939-5038d09764d0.png)


When I add a filesystem via FS GUI, I only can select the md0 - no mapper! - and then it looks so:
![grafik](https://user-images.githubusercontent.com/1151915/55141006-b0a37980-5139-11e9-8abb-ba85a8384fbe.png)

and the cyrpt is gone:
![grafik](https://user-images.githubusercontent.com/1151915/55141034-c4e77680-5139-11e9-936e-d0b9ce059055.png)


Either your description is wrong at a certain step, or OMV or OMV-LUKS-Plugin is broken.

**Comment by subzero79** [comment]
The block device md0 needs to be decrypted for it to appear as device mapper.

**Comment by Wikinaut** [comment]
How, when it is not listed (see above)?

**Comment by subzero79** [comment]
See your first screenshot, md0 formatted as LUKS, locked.

**Comment by Wikinaut** [comment]
No, it is then this view (empty!):

![grafik](https://user-images.githubusercontent.com/1151915/55161534-10b01500-5166-11e9-8146-04fd50f9ef97.png)

**Comment by Wikinaut** [comment]
Only, when I create the RAID > LUKS **manually** (on the commandline), I do see this:

![grafik](https://user-images.githubusercontent.com/1151915/55161587-2c1b2000-5166-11e9-87d6-25e96fd2d9a7.png)


So: something wrong with the OMV modules.

**Comment by subzero79** [comment]
You post this before, why didn't you unlock the disk then?

https://user-images.githubusercontent.com/1151915/55141192-23145980-513a-11e9-9021-04bf6da1d829.png

**Comment by Wikinaut** [comment]
@subzero79 perhaps because I asked for a **detailed** step-by-step (with screenshots) explanation, but you failed to explain that above in your post https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-luksencryption/issues/24#issuecomment-476412145 ? Or did I overlook that statement?

**Comment by subzero79** [comment]
Sorry but i don't have time to give you a personal tutorial with screenshots, maybe someone on the forum can do that for you. For me the interface is pretty intuitive, the column (at least in English) says unlock and is greyed (unfilled) which one (and several users of the plugin) would assume it isn't unlock, goes filled blue when is unlocked, so is just a matter of selecting the device and press unlock.

This is the old post from the user who created this plugin giving some details about it

http://forum.openmediavault.org/index.php/Thread/11592-LUKS-disk-encryption-plugin/?postID=95883&highlight=luks%2Bplugin%2Busage#post95883

Not many people look here, so you will get better support of plugin usage at the forum

**Comment by subzero79** [comment]
When you have time and if you can (have the disk reformatted or so) can you submit the actual paraphrase you used so I can test it in omv5

**Comment by evanvosberg** [comment]
This issue is closed but no solution has been documented here.

I came across the same issue in OMV 7, but it turned out to be not an issue of the `openmediavault-luksencryption` plugin, rather than an **issue of OMV itself**.

## General

There are different ways of configuring a LUKS encrypted file system with RAID, but all have in common that it's a setup of three layers while the order of the layers might vary.

The three layers I wanted to setup:
1. RAID
2. LUKS encryption
3. file system

## OMV Setup

In the native OMV Web UI you basically start with creating a file system and along with the you have the option to setup RAID. So in the UI setting up RAID and creating the file system is bundled in a single step, while it performs several steps in the background. 

### Single disk setup with LUKS

1. enable LUKS with the `openmediavault-luksencryption` plugin
2. create a file system on the LUKS crypt container in OMV

This works fine

### RAID setup with LUKS

1. enable LUKS with the `openmediavault-luksencryption` plugin
2. create a file system with RAID on the LUKS crypt containers in OMV

The create RAID step performed by OMV in the background will remove the LUKS crypt container and then create an unencrypted file system. **So this approach fails.**

#### Solution

Create RAID manually **on the command line**.

1. create your RAID configuration
2. setup LUKS on to p of your RAID
3. create a file system on top of the LUKS crypt container

Once you have done this on the command line, the crypt containers will appear in `openmediavault-luksencryption` plugin and can be unlocked there, them you can also mount them in OMV.

**Comment by ryecoaaron** [comment]
> The create RAID step performed by OMV in the background will remove the LUKS crypt container and then create an unencrypted file system. So this approach fails.

It is impossible for raid to remove the luks containers unless you pick the physical devices in the raid creation instead of the luks containers.

- I just created two luks containers on /dev/vdi and /dev/vdj
- This created two containers /dev/mapper/vdi-crypt and /dev/mapper/vdj-crypt
- I created a mdadm raid 1 device using /dev/mapper/vdi-crypt and /dev/mapper/vdj-crypt.  If you choose /dev/vdi and /dev/vdj, you will wipe the containers.
- This created /dev/md0
- I created an ext4 filesystem on /dev/md0
- I mounted the filesystem

Everything works fine and no command line needed.

I understand the raid creation dialog gives you the option to create a raid array using the physical devices but it has always been that way.  OMV adds all devices without a filesystem on them.  Technically, a new luks container does not have a filesystem on it.
