### ISSUE TITLE
Support TPM for unlocking LUKS disks

### ISSUE THREAD

**Issue by kowalski7cc** [OpenMediaVault-Plugin-Developers/openmediavault-luksencryption#9]
Allow the TPM to unlock automatically a disk without password:
https://github.com/shpedoikal/tpm-luks

**Comment by imgrant** [comment]
This does look nifty, but I'm unlikely to add it. Not least because I don't have a machine with a TPM nor does it seem possible/simple to emulate one in VirtualBox.
I suspect the development cost would outweigh the usage. I think this will have to be left to users who want to do this implementing it for themselves on the command line.
Happy to consider patches, though.
